<link rel="stylesheet" href="<?php echo $this->getSkinurl('css/customshirt.css'); ?>" />

<script src="<?php echo $this->getSkinurl('js/jquery-ui.js'); ?>"></script>
<script src="<?php echo $this->getSkinurl('js/custom-script.js'); ?>"></script>
<script src="<?php echo $this->getSkinurl('js/html2canvas.js'); ?>"></script>
<!--<script src="<?php echo $this->getSkinurl('js/jquery.plugin.html2canvas.js'); ?>"></script>-->

<form class="inner" method="post" action="<?php echo Mage::getUrl().'customizeshirt/index/addtocart' ?>" id="customizeshirtform">
<fieldset id="partShirt">

<div class="customize-container">
<div class="left-cont">
<div id="accordion">
  <h3 class="fabric_tab">SELECT FABRIC</h3>
  <div class="fabrics">
  <ul class="items-list">
    <?php
		$category_id = '6';
		$products = Mage::getModel('catalog/category')->load($category_id)
		 ->getProductCollection()
		 ->addAttributeToSelect('*')
		 ->addAttributeToFilter('status', 1)
		 ->addAttributeToFilter('visibility', 4)
		 ->setOrder('price', 'ASC');
		foreach($products as $product) { ?>
		<li onclick="GetFabric('<?php echo Mage::helper('catalog/image')->init($product, 'thumbnail'); ?>','<?php echo $product->getShortDescription(); ?>','<?php echo $product->getName(); ?>');">
		<!--<span class="PriceShirt"><?php echo Mage::helper('core')->currency($product->getPrice(), true, false); ?></span>-->
		<img width="75" height="75" onclick="fabricClick('<?php echo $product->getId(); ?>', '<?php echo Mage::helper('core')->currency($product->getPrice(), true, false); ?>','<?php echo $product->getName(); ?>','<?php echo Mage::helper('core')->currency($product->getPrice(), true, false); ?>','<?php echo $product->getShortDescription(); ?>');" style="cursor:pointer" alt="" src="<?php echo Mage::helper('catalog/image')->init($product, 'thumbnail')->resize(75); ?>"/>
		</li>
		<?php } ?>
		</ul>
		<div id="fabricslideimg"></div>
		<div style="clear:both;"></div>
  </div>
  <h3  class="style_tab">SELECT STYLE</h3>
  <div class="shirt-style">
   <ul class="tabs">
   	 <li class="plus1"><a href="#tab1">Sleeve</a></li>
     <li class="plus1"><a href="#tab2">Collar</a></li>
	 <li class="plus1"><a href="#tab3">Cuff</a></li>
	 <li class="plus1"><a href="#tab4">Front</a></li>
	 <li class="plus1"><a href="#tab5">Shoulder</a></li>
   </ul>
  <div class="tab_container">
  	<div id="tab1" class="tab_content shirt-sleeve-style">
  		<?php $collection = Mage::getModel('customizeshirt/sleeve')
  			  	->getCollection()
  			  	->addFieldToFilter('status', 1)
  			  	->setOrder('sleeve_id', 'ASC');
  		?>
  		<ul class="items-list sleeve-style">
	  		<?php foreach ($collection as $sleeve) { ?>
	  			<li onclick="GetSleeve('<?php echo $sleeve->getSleeveTitle(); ?>', '<?php echo Mage::getBaseUrl('media').$sleeve->getSleeveImage(); ?>')">
	  				<a onclick="SleeveClick('<?php echo $sleeve->getSwitchno(); ?>')"><img width="80" alt="" src="<?php echo Mage::getBaseUrl('media').$sleeve->getSleeveImage(); ?>"><strong><?php echo $sleeve->getSleeveTitle(); ?></strong></a>
	  			</li>
	  		<?php } ?>
	  	</ul>
	  	<div id="sleeveslideimg"></div>
  	</div>
    <div id="tab2" class="tab_content shirt-collar-style">
    <ul class="items-list collar-style">
    <?php $collection = Mage::getModel('customizeshirt/collar')->getCollection()
			->addFieldToFilter('status', 1)
			->setOrder('collar_id', 'ASC');
	foreach($collection as $collar) { ?>
		<li collar="<?php echo $collar->getSwitchno(); ?>" onclick="GetCollar('<?php echo $collar->getCollarTitle(); ?>','<?php echo Mage::getBaseUrl('media').$collar->getCollarImage(); ?>');" class="">
		<a onclick="CollarClick(<?php echo $collar->getSwitchno(); ?>)"><img width="80" alt="" src="<?php echo Mage::getBaseUrl('media').$collar->getCollarImage(); ?>"><strong><?php echo $collar->getCollarTitle(); ?></strong></a>
		</li>
	<?php } ?>
	</ul>
	<div id="collarslideimg"></div>
	</div>
	
	<div id="tab3" class="tab_content shirt-cuff-style">
    <ul class="items-list cuff-style">
    <?php $collection = Mage::getModel('customizeshirt/cuff')->getCollection()
			->addFieldToFilter('status', 1)
			->setOrder('cuff_id', 'ASC');
	foreach($collection as $cuff) { ?>
		<li onclick="GetCuff('<?php echo $cuff->getCuffTitle(); ?>','<?php echo Mage::getBaseUrl('media').$cuff->getCuffImage(); ?>');" class="">
		<a onclick="CuffClick(<?php echo $cuff->getSwitchno(); ?>)"><img width="80" alt="" src="<?php echo Mage::getBaseUrl('media').$cuff->getCuffImage(); ?>"><strong><?php echo $cuff->getCuffTitle(); ?></strong></a>
		</li>
	<?php } ?>
	</ul>
	<div id="cuffslideimg"></div>
	</div>
	
	<div id="tab4" class="tab_content shirt-front-style">
    <ul class="items-list front-style">
    <?php $collection = Mage::getModel('customizeshirt/front')->getCollection()
			->addFieldToFilter('status', 1)
			->setOrder('front_id', 'ASC');
	foreach($collection as $front) { ?>
		<li onclick="GetFront('<?php echo $front->getFrontTitle(); ?>','<?php echo Mage::getBaseUrl('media').$front->getFrontImage(); ?>');" class="">
		<a onclick="placketClick(<?php echo $front->getSwitchno(); ?>)"><img width="80" alt="" src="<?php echo Mage::getBaseUrl('media').$front->getFrontImage(); ?>"><strong><?php echo $front->getFrontTitle(); ?></strong></a>
		</li>
	<?php } ?>
	</ul>
	<div id="frontslideimg"></div>
	</div>
	<div id="tab5" class="tab_content shirt-shoulder-style">
    <ul class="items-list shoulder-style">
    <?php $collection = Mage::getModel('customizeshirt/shoulder')->getCollection()
			->addFieldToFilter('status', 1)
			->setOrder('shoulder_id', 'ASC');
	foreach($collection as $shoulder) { ?>
		<li onclick="GetShoulder('<?php echo $shoulder->getShoulderTitle(); ?>','<?php echo Mage::getBaseUrl('media').$shoulder->getShoulderImage(); ?>');" class="">
		<a onclick="ShoulderClick(<?php echo $shoulder->getSwitchno(); ?>)"><img width="80" alt="" src="<?php echo Mage::getBaseUrl('media').$shoulder->getShoulderImage(); ?>"><strong><?php echo $shoulder->getShoulderTitle(); ?></strong></a>
		</li>
	<?php } ?>
	</ul>
	<div id="shoulderslideimg"></div>
	</div>
	
   </div>
	
	<div style="clear:both;"></div>
  </div>
  <h3 class="contrast_tab">SELECT COLOR CONTRAST</h3>
  <div class="shirt-color-contrast">
	<?php echo $this->getLayout()->createBlock('customizeshirt/customizeshirt')->setTemplate('customizeshirt/colorcontrast.phtml')->toHtml(); ?>
  </div>
  <h3 class="monogram_tab">PERSONALIZE / MONOGRAM</h3>
  <div class="shirt-personalize">
   <?php echo $this->getLayout()->createBlock('customizeshirt/customizeshirt')->setTemplate('customizeshirt/personalize.phtml')->toHtml(); ?>
  </div>
  <h3 class="measure_tab">MEASUREMENTS</h3>
  <div class="shirt-measurements">
    <?php echo $this->getLayout()->createBlock('customizeshirt/customizeshirt')->setTemplate('customizeshirt/measurements.phtml')->toHtml(); ?>
  </div>
</div>

<script>
  jQuery(function() {
    jQuery( "#accordion" ).accordion({
      heightStyle: "content"
    });
  });
  </script>
  
  </div>
 
<div class="right-cont">
<div id="shirt">
<div id="sba5" style="position: absolute; top: 0px; right: 0px;">
<img id="sba5img" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>customize/StandardSleeve_WhiteLineIssueSolver.png" alt="">
</div>
<div id="sba" style="position: absolute; top: 0px; right: 0px;">
<img id="sbaimg" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>customize/3_main_set2_0003.png">
</div>
<div id="ssl" style="position: absolute; top: 0px; right: 0px;">
<img id="sslimg" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>customize/3_main_set2_0000.png">
</div>
<div id="scu" style="position: absolute; top: 0px; right: 0px;">
<img id="scuimg" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>customize/3_main_set1_0006.png">
</div>
<div id="sba1" style="position: absolute; top: 0px; right: 0px;">
<img id="sba1img" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>customize/blank.png">
</div>
<div id="spl" style="position: absolute; top: 0px; right: 0px;">
<img id="splimg" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>customize/3_main_set3_0012.png">
</div>
<div id="sco_neru" style="position: absolute; top: 0px; right: 0px;">
<img id="scoimg_neru" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>customize/blank.png">
</div>
<div id="sco" style="position: absolute; top: 0px; right: 0px;">
<img id="scoimg" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>customize/3_main_set3_0002.png">
</div>
<div id="scob" style="position: absolute; top: 0px; right: 0px;">
<img id="scobimg" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>customize/1_main_button_0002.png">
</div>
<div id="scobd" style="position: absolute; top: 0px; right: 0px;">
<img id="scobdimg" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>customize/blank.png">
</div>
<div id="spo" style="position: absolute; top: 0px; right: 0px;">
<img id="spoimg" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>customize/blank.png">
</div>
<div id="ssh" style="position: absolute; top: 0px; right: 0px;">
<img id="sshimg" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>customize/blank.png">
</div>
<div id="sshb" style="position: absolute; top: 0px; right: 0px;">
<img id="sshbimg" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>customize/blank.png">
</div>
<div id="scol" style="position: absolute; top: 0px; right: 0px;">
<img id="scolimg" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>customize/3_main_set3_0004.png">
</div>
<div id="scsic" style="position: absolute; top: 0px; right: 0px;">
<img id="scsicimg" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>customize/blank.png">
</div>
<div id="scui" style="position: absolute; top: 0px; right: 0px;">
<img id="scuiimg" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>customize/blank.png">
</div>
<div id="sba3" style="position: absolute; top: 0px; right: 0px;">
<img id="sba3img" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>customize/1_main_button_0004.png">
</div>
<div id="sba4" style="position: absolute; top: 0px; right: 0px;">
<img id="sba4img" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>customize/blank.png">
</div>
<!--<div id="zoomcuff" onmouseout="zoomHide()" onmouseover="zoomShow(2)">
<img id="zoomcuffimg" width="32" height="32" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>customize/zoom_in.png" alt="">
</div>
<div id="zoomcollar" onmouseout="zoomHide()" onmouseover="zoomShow(1)">
<img id="zoomcollarimg" width="32" height="32" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>customize/zoom_in.png" alt="">
</div>
<div id="zoomshoulder" onmouseout="zoomHide()" onmouseover="zoomShow(3)">
<img id="zoomshoulderimg" width="32" height="32" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>customize/zoom_in.png" alt="">
</div>
<div id="zoompocket" onmouseout="zoomHide()" onmouseover="zoomShow(4)">
<img id="zoompocketimg" width="32" height="32" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>customize/zoom_in.png" alt="">
</div>
<div id="zoomcuffinner" onmouseout="zoomHide()" onmouseover="zoomShow(5)">
<img id="zoomcuffinnerimg" width="32" height="32" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>customize/zoom_in.png" alt="">
</div>-->
</div>

<a onclick="UndoFunction()" style="cursor:pointer">Undo</a>

<div class="col">
<h4>Shirt Summary</h4>
<ul>
<li>
<span id="TitleFabric"></span>
</li>
<li id="CollarDisc"></li>
<li id="CuffDisc"></li>
<li id="PlacketDisc"></li>
<li id="PocketDisc"></li>
<li id="ShoulderDisc"></li>
<li id="ButtonsDisc"></li>
<li id="CollarcolorDisc"></li>
<li id="CollarliningcolorDisc"></li>
<li id="CuffinnercolorDisc"></li>
<li id="CuffcolorDisc"></li>
<li id="PlacketcolorDisc"></li>
<li id="PocketcolorDisc"></li>
<li id="StrapcolorDisc"></li>
<li id="MonoDisc"></li>
<li id="LabelDisc"></li>
</ul>
</div>

</div>
</div>

  
<div id="UndoButton" style="visibility: hidden; width: 0px; height: 0px">
	<input id="un" type="button" onclick="UndoFabric('Collar',858);">
</div>

<input id="server" type="hidden" value="http://localhost/projects/prestine/" name="server">
<input id="IsFabrics" type="hidden" value="False" name="IsFabrics" data-val-required="The Boolean field is required." data-val="true">
<input id="page" type="hidden" value="1" name="page">
<input id="lookupFabric" type="hidden" value="" name="lookupFabric">
<input id="fapricType" type="hidden" value="1" name="fapricType">
<input id="stepHiden" type="hidden" value="0" name="stepHiden">
<input id="CurrentType" type="hidden" value="" name="CurrentType">
<input id="SizeType" type="hidden" value="AskOurTailors" name="SizeType" data-val-required="The SizeType field is required." data-val="true">
<input id="Id" type="hidden" value="-1" name="Id" data-val-required="The Id field is required." data-val-number="The field Id must be a number." data-val="true">
<input id="SessionKey" type="hidden" value="00000000-0000-0000-0000-000000000000" name="SessionKey" data-val-required="The SessionKey field is required." data-val="true">
<input id="back" type="hidden" value="" name="back" data-val-number="The field back must be a number." data-val="true">
<input id="basecolor" type="hidden" value="3" name="basecolor">
<input id="bodytype" type="hidden" value="" name="bodytype" data-val-number="The field bodytype must be a number." data-val="true">
<input id="branding" type="hidden" value="" name="branding" data-val-number="The field branding must be a number." data-val="true">
<input id="brandingcolor" type="hidden" value="" name="brandingcolor">
<input id="brandingtext" type="hidden" value="" name="brandingtext">
<input id="buttons" type="hidden" value="1" name="buttons" data-val-number="The field buttons must be a number." data-val="true">
<input id="collar" type="hidden" value="1" name="collar" data-val-number="The field collar must be a number." data-val="true">
<input id="collarcolor" type="hidden" value="3" name="collarcolor">
<input id="collarlabel" type="hidden" value="" name="collarlabel" data-val-number="The field collarlabel must be a number." data-val="true">
<input id="collarlining" type="hidden" value="0" name="collarlining" data-val-number="The field collarlining must be a number." data-val="true">
<input id="collarliningcolor" type="hidden" value="3" name="collarliningcolor">
<input id="collarmono" type="hidden" value="" name="collarmono" data-val-number="The field collarmono must be a number." data-val="true">
<input id="cuff" type="hidden" value="1" name="cuff" data-val-number="The field cuff must be a number." data-val="true">
<input id="cuffcolor" type="hidden" value="3" name="cuffcolor">
<input id="cuffinner" type="hidden" value="0" name="cuffinner" data-val-number="The field cuffinner must be a number." data-val="true">
<input id="cuffinnercolor" type="hidden" value="977" name="cuffinnercolor">
<input id="cuffmono" type="hidden" value="" name="cuffmono" data-val-number="The field cuffmono must be a number." data-val="true">
<input id="cuffsleeve" type="hidden" value="0" name="cuffsleeve" data-val-number="The field cuffsleeve must be a number." data-val="true">
<input id="cuffsleevecolor" type="hidden" value="977" name="cuffsleevecolor">
<input id="customcollar" type="hidden" value="False" name="customcollar">
<input id="customplacket" type="hidden" value="False" name="customplacket">
<input id="custompocket" type="hidden" value="False" name="custompocket">
<input id="customstrap" type="hidden" value="False" name="customstrap">
<input id="cut" type="hidden" value="" name="cut" data-val-number="The field cut must be a number." data-val="true">
<input id="cutomcuff" type="hidden" value="False" name="cutomcuff">
<input id="heightft" type="hidden" value="" name="heightft" data-val-number="The field heightft must be a number." data-val="true">
<input id="heightin" type="hidden" value="" name="heightin" data-val-number="The field heightin must be a number." data-val="true">
<input id="monocolor" type="hidden" value="" name="monocolor">
<input id="monotext" type="hidden" value="" name="monotext">
<input id="placket" type="hidden" value="1" name="placket" data-val-number="The field placket must be a number." data-val="true">
<input id="placketcolor" type="hidden" value="3" name="placketcolor">
<input id="placketlabel" type="hidden" value="" name="placketlabel" data-val-number="The field placketlabel must be a number." data-val="true">
<input id="pocket" type="hidden" value="1" name="pocket" data-val-number="The field pocket must be a number." data-val="true">
<input id="pocketcolor" type="hidden" value="3" name="pocketcolor">
<input id="pocketmono" type="hidden" value="" name="pocketmono" data-val-number="The field pocketmono must be a number." data-val="true">
<input id="pocketstyle" type="hidden" value="1" name="pocketstyle" data-val-number="The field pocketstyle must be a number." data-val="true">
<input id="shirtarms" type="hidden" value="" name="shirtarms">
<input id="shirtneck" type="hidden" value="" name="shirtneck">
<input id="shirtprice" type="hidden" value="125" name="shirtprice" data-val-number="The field shirtprice must be a number." data-val="true">
<input id="labelcolor" type="hidden" value="" name="labelcolor">
<input id="labeltext" type="hidden" value="" name="labeltext">
<input id="sizing" type="hidden" value="" name="sizing" data-val-number="The field sizing must be a number." data-val="true">
<input id="sizingtext" type="hidden" value="" name="sizingtext">
<input id="split" type="hidden" value="" name="split">
<input id="splittext" type="hidden" value="" name="splittext">
<input id="splittextcolor" type="hidden" value="" name="splittextcolor">
<input id="strap" type="hidden" value="1" name="strap" data-val-number="The field strap must be a number." data-val="true">
<input id="strapcolor" type="hidden" value="3" name="strapcolor">
<input id="sleeve" type="hidden" value="" name="sleeve" data-val-number="The field strap must be a number." data-val="true">
<input id="sleeve_case" type="hidden" value="1" name="sleeve_case" data-val-number="The field strap must be a number." data-val="true">
<input id="tuck" type="hidden" value="" name="tuck" data-val-number="The field tuck must be a number." data-val="true">
<input id="weight" type="hidden" value="" name="weight" data-val-number="The field weight must be a number." data-val="true">
<input id="monogramfont" type="hidden" value="0" name="monogramfont" data-val-required="The monogramfont field is required." data-val-number="The field monogramfont must be a number." data-val="true">
<input id="labelfont" type="hidden" value="0" name="labelfont" data-val-required="The labelfont field is required." data-val-number="The field labelfont must be a number." data-val="true">

<input type="hidden" name="img_val" id="img_val" value="" />

</fieldset>
</form>

  <input type="button" value="Add to cart" onclick="capture();" />
  <script type="text/javascript">
	   function capture() {
			html2canvas(jQuery("#shirt"), {
				onrendered: function (canvas) {
					jQuery('#img_val').val(canvas.toDataURL("image/png"));
					document.getElementById("customizeshirtform").submit();
				}
			});
		}
	</script>

  <script type="text/javascript">
  jQuery(document).ready(function() {
  //jQuery('#basecolor').val();
  //fabricClick('<?php echo $product->getId(); ?>', '<?php echo Mage::helper('core')->currency($product->getPrice(), true, false); ?>','<?php echo $product->getName(); ?>','<?php echo Mage::helper('core')->currency($product->getPrice(), true, false); ?>','<?php echo $product->getShortDescription(); ?>'); 
  //GetFabric('<?php echo Mage::helper('catalog/image')->init($product, 'thumbnail')->resize(175); ?>','<?php echo $product->getShortDescription(); ?>','<?php echo $product->getName(); ?>');
   // jQuery('#someLinkId').click();
  });
  function GetFabric(url, discription, name) {
        var data = "<div style='position: relative;'><div class='img'>" + "<img src='" + url + "' alt='' width='175' height='175' /></div><a href='#largefabric' class='zoomfabric'>zoom</a></div> <div style='display:none'><div id='largefabric'><img src='" + url + "' alt='' /></div></div>";
        jQuery('#fabricslideimg').html(data);
        jQuery('#fabricslideimg').show();
			jQuery(".zoomfabric").fancybox({
			'titlePosition'		: 'inside',
			'transitionIn'		: 'none',
			'transitionOut'		: 'none'
			});
    }

    function GetSleeve(title, url)
    {
    	var data = "<div style='position: relative;'><div class='img'>" + "<img src='" + url + "' alt='' /></div></div>";
        jQuery('#sleeveslideimg').html(data);
        jQuery('#sleeveslideimg').show();
    }

	function GetCollar(title, url) 
	{
        var data = "<div style='position: relative;'><div class='img'>" + "<img src='" + url + "' alt='' /></div></div>";
        jQuery('#collarslideimg').html(data);
        jQuery('#collarslideimg').show();
    }
	function GetCuff(title, url) 
	{
        var data = "<div style='position: relative;'><div class='img'>" + "<img src='" + url + "' alt='' /></div></div>";
        jQuery('#cuffslideimg').html(data);
        jQuery('#cuffslideimg').show();
    }
	function GetFront(title, url) 
	{
        var data = "<div style='position: relative;'><div class='img'>" + "<img src='" + url + "' alt='' /></div></div>";
        jQuery('#frontslideimg').html(data);
		//jQuery('.shirt-style .tab_content ul.items-list li').removeClass('active');
        //jQuery(this).addClass('active');
    }
	function GetShoulder(title, url) 
	{
        var data = "<div style='position: relative;'><div class='img'>" + "<img src='" + url + "' alt='' /></div></div>";
        jQuery('#shoulderslideimg').html(data);
		//jQuery('.shirt-style .tab_content ul.items-list li').removeClass('active');
        //jQuery(this).addClass('active');
    }
	</script>
	<script type="text/javascript">
	jQuery(document).ready(function() {
	//On hover Event
	jQuery("h3.style_tab").hover(function() {
	if(jQuery(".style_tab").hasClass("ui-corner-all")) {
	//When accordion clicks...
	jQuery(".shirt-style .tab_content").hide(); //Hide all content
	jQuery(".shirt-style ul.tabs li").removeClass("active");
	jQuery(".shirt-style ul.tabs li:first").addClass("active").show(); //Activate first tab
	jQuery(".shirt-style .tab_content:first").show(); //Show first tab content
	}
	});
	
	jQuery("h3.contrast_tab").hover(function() {
	if(jQuery(".contrast_tab").hasClass("ui-corner-all")) {
	//When accordion clicks...
	jQuery(".shirt-color-contrast .tab_content").hide(); //Hide all content
	jQuery(".shirt-color-contrast ul.tabs li").removeClass("active");
	jQuery(".shirt-color-contrast ul.tabs li:first").addClass("active").show(); //Activate first tab
	jQuery(".shirt-color-contrast .tab_content:first").show(); //Show first tab content
	}
	});
	
	jQuery("h3.monogram_tab").hover(function() {
	if(jQuery(".monogram_tab").hasClass("ui-corner-all")) {
	//When accordion clicks...
	jQuery(".shirt-personalize .tab_content").hide(); //Hide all content
	jQuery(".shirt-personalize ul.tabs li").removeClass("active");
	jQuery(".shirt-personalize ul.tabs li:first").addClass("active").show(); //Activate first tab
	jQuery(".shirt-personalize .tab_content:first").show(); //Show first tab content
	}
	});
	
	jQuery("h3.measure_tab").hover(function() {
	if(jQuery(".measure_tab").hasClass("ui-corner-all")) {
	//When accordion clicks...
	jQuery(".shirt-measurements .tab_content").hide(); //Hide all content
	jQuery(".shirt-measurements ul.tabs li").removeClass("active");
	jQuery(".shirt-measurements ul.tabs li:first").addClass("active").show(); //Activate first tab
	jQuery(".shirt-measurements .tab_content:first").show(); //Show first tab content
	}
	});
	});
	</script>
	
	


