   <ul class="tabs">
     <li class="plus1" id="measure"><a href="#measurements_tab1">Measurements</a></li>
	 <li class="plus1" id="stdmeasure"><a href="#measurements_tab2">Standard measurements</a></li>
   </ul>
  <div class="tab_container">
    <div id="measurements_tab1" class="tab_content shirt-measurements">
	
	<div class="row_cont">
	<div class="row">
	<div class="input-box">
	<label for="neck">Neck</label>
	<input id="neck" type="text" value="" name="neck" maxlength="5">
	</div>
	
	<div class="input-box">
	<label for="chest">Chest</label>
	<input id="chest" type="text" value="" name="chest" maxlength="5">
	</div>
	
	<div class="input-box">
	<label for="waist">Waist</label>
	<input id="waist" type="text" value="" name="waist" maxlength="5">
	</div>
	</div>

	<div class="row">
	<div class="input-box">
	<label for="hip">Hip</label>
	<input id="hip" type="text" value="" name="hip" maxlength="5">
	</div>
	
	<div class="input-box">
	<label for="length">Lenght</label>
	<input id="length" type="text" value="" name="length" maxlength="5">
	</div>
	
	<div class="input-box">
	<label for="shoulder">Shoulder</label>
	<input id="shoulder" type="text" value="" name="shoulder" maxlength="5">
	</div>
	<div class="input-box">
	<label for="sleevelength">Sleeve</label>
	<input id="sleevelength" type="text" value="" name="sleevelength" maxlength="5">
	</div>
	</div>
	</div>
	
	<div class="video_container"></div>
	<script type="text/javascript">
	jQuery('#neck').focus( function(){
		jQuery('.video_container').html('<h4>Neck</h4><iframe width="215" height="190" src="//www.youtube.com/embed/yxyLu5_6nSU?autoplay=1&loop=1&playlist=yxyLu5_6nSU" frameborder="0" allowfullscreen></iframe>');
	})
	jQuery('#chest').focus( function(){
		jQuery('.video_container').html('<h4>Chest</h4><iframe width="215" height="190" src="//www.youtube.com/embed/G1MlnP3PfO0?autoplay=1&loop=1&playlist=G1MlnP3PfO0" frameborder="0" allowfullscreen></iframe>');
	})
	jQuery('#waist').focus( function(){
		jQuery('.video_container').html('<h4>Waist</h4><iframe width="215" height="190" src="//www.youtube.com/embed/rcCeWjUDHt8?autoplay=1&loop=1&playlist=rcCeWjUDHt8" frameborder="0" allowfullscreen></iframe>');
	})
	jQuery('#hip').focus( function(){
		jQuery('.video_container').html('<h4>Hip</h4><iframe width="215" height="190" src="//www.youtube.com/embed/zC0CR83yA1U?autoplay=1&loop=1&playlist=zC0CR83yA1U" frameborder="0" allowfullscreen></iframe>');
	})
	
	jQuery('#length').focus( function(){
		jQuery('.video_container').html('<h4>Length</h4><iframe width="215" height="190" src="//www.youtube.com/embed/zlSkY2YXC5k?autoplay=1&loop=1&playlist=zlSkY2YXC5k" frameborder="0" allowfullscreen></iframe>');
	})
	
	jQuery('#shoulder').focus( function(){
		jQuery('.video_container').html('<h4>Shoulder</h4><iframe width="215" height="190" src="//www.youtube.com/embed/8IK4k6uPQLo?autoplay=1&loop=1&playlist=8IK4k6uPQLo" frameborder="0" allowfullscreen></iframe>');
	})
	jQuery('#sleevelength').focus( function(){
		jQuery('.video_container').html('<h4>Sleeve</h4><iframe width="215" height="190" src="//www.youtube.com/embed/jmLqg6edHkg?autoplay=1&loop=1&playlist=jmLqg6edHkg" frameborder="0" allowfullscreen></iframe>');
	})
	</script>
	</div>
	
	<div id="measurements_tab2" class="tab_content shirt-std-measurements">
	<label>Select Your Size</label>
	<select id="stdsizes" class="valid" name="stdsizes">
	 <option value="">Select</option>
	 <option value="S">S</option>
	 <option value="M">M</option>
	 <option value="L">L</option>
	 <option value="XL">XL</option>
	 <option value="XXL">XXL</option>
	</select>
	
	</div>
	</div>
	
<div style="clear:both;"></div>