<div class="suggestions-area">
<h3>Suggestions for you:</h3>
	<ul>
	  <li><img src="<?php echo $this->getSkinurl('images/customshirt/blue.png'); ?>" alt="" /></li>
	  <li><img src="<?php echo $this->getSkinurl('images/customshirt/brown.png'); ?>" alt="" /></li>
	  <li><img src="<?php echo $this->getSkinurl('images/customshirt/pink.png'); ?>" alt="" /></li>
	  <li><img src="<?php echo $this->getSkinurl('images/customshirt/gray.png'); ?>" alt="" /></li>
	</ul>
</div>
